//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.01 at 10:20:49 PM CST 
//


package com.founderdpt.comm.xworld.orm.mapping.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.founderdpt.comm.xworld.orm.mapping.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.founderdpt.comm.xworld.orm.mapping.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XworldMapping }
     * 
     */
    public XworldMapping createXworldMapping() {
        return new XworldMapping();
    }

    /**
     * Create an instance of {@link XworldMapping.Column }
     * 
     */
    public XworldMapping.Column createXworldMappingColumn() {
        return new XworldMapping.Column();
    }

    /**
     * Create an instance of {@link XworldMapping.Column.Generator }
     * 
     */
    public XworldMapping.Column.Generator createXworldMappingColumnGenerator() {
        return new XworldMapping.Column.Generator();
    }

    /**
     * Create an instance of {@link XworldMapping.Id }
     * 
     */
    public XworldMapping.Id createXworldMappingId() {
        return new XworldMapping.Id();
    }

    /**
     * Create an instance of {@link XworldMapping.Id.Generator }
     * 
     */
    public XworldMapping.Id.Generator createXworldMappingIdGenerator() {
        return new XworldMapping.Id.Generator();
    }

    /**
     * Create an instance of {@link XworldMapping.Column.Generator.Param }
     * 
     */
    public XworldMapping.Column.Generator.Param createXworldMappingColumnGeneratorParam() {
        return new XworldMapping.Column.Generator.Param();
    }

    /**
     * Create an instance of {@link XworldMapping.Id.Generator.Param }
     * 
     */
    public XworldMapping.Id.Generator.Param createXworldMappingIdGeneratorParam() {
        return new XworldMapping.Id.Generator.Param();
    }

}
